### PR TITLE
Integrate with Travis CI

### PR DESCRIPTION
**Pull request by viciious**
The builds are failing at the moment due to broken cursor API in Python and Lua bindings but that's something I'm going to leave out of the scope of this PR.

### CODE REVIEW

**Comment by mikke89** [comment]
I haven't actually used Travis before, but let's try it out!

**Comment by viciious** [comment]
You first need to login to travis, link your account and enable builds for librocket repository

**Comment by mikke89** [comment]
Yup, I have it up and running, the build fails for now though. Not sure why the badge says unknown.

**Comment by viciious** [comment]
Out of curiosity, why have you not merged this PR though? The submitted code ended up in the repository anyway but without the proper authorship?

**Comment by mikke89** [comment]
I'm not sure I follow. I did merge it as far as I know?

man. 6. mai 2019, 09.45 skrev Victor Luchits <notifications@github.com>:

**Comment by viciious** [comment]
Well, you kinda did but none of the original commits made it into the master branch.

**Comment by mikke89** [comment]
Oh, I see now. I cherry picked it into the master branch because we can't merge it the normal way (which would bring all the cpp11 things in). I'm not sure what is the right way to do this? I guess the right way is to have PRs on the master branch so we can merge it to cpp11 branch after. What do you think?

**Comment by viciious** [comment]
Don't you intend to merge the cpp11 branch into master anyway?

**Comment by viciious** [comment]
Imo it's not worth the hassle to maintain it in a separate branch as you actually gain nothing from it

**Comment by mikke89** [comment]
My intention was really to keep working with c++17 on the master branch. I'm not sure how well the conversion to 11 would go for the performance branch either.

**Comment by viciious** [comment]
Oh well, I can't really then contribute to the project as I'm stuck with C++11 for the foreseeable future and porting stuff between the two branches is simply too much work for me.

**Comment by mikke89** [comment]
:( Noo. Alright, I might reconsider it then. I was hoping things would catch up sooner.

**Comment by mikke89** [comment]
But you're right, it was already a hassle to keep the two branches in synch. I'll go ahead and merge it tonight.

**Pull request merged**
