### PR TITLE
Fix C++11 and GCC compatibility

### PR DESCRIPTION
**Pull request by barotto**
Tested only with GCC 5.4.0
It compiles correctly but code is untested.

### CODE REVIEW

**Comment by mikke89** [comment]
Thanks for the pull request! I think it's better to to replace the make_unique rather than reimplementing it, especially in the std namespace as that may cause issues. 

I'll go ahead and make a new commit inspired by this one.

**Comment by barotto** [comment]
> Don't want to sound nitpicky but make_unique.h is missing license header

Yeah, I'm not sure about the licence either.
I took the code from https://isocpp.org/files/papers/N3656.txt
Given the source I assumed it would be fine to include, but it's better to replace rather than reimplementing.

**Comment by mikke89** [comment]
Added a new commit, does it work for you?

**Comment by barotto** [comment]
It does work for me.

**Comment by mikke89** [comment]
Great!

**Pull request closed without merging**
